# .github/workflows/workflow-subtract.yml
name: Subtract Workflow

on: [push]

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install pytest

  run-subtract-tests:
    runs-on: ubuntu-latest
    needs: prepare-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Subtract Tests
        run: pytest -k "test_subtract"
